### PR TITLE
Add Magento 3.5.1

### PR DESCRIPTION
**Pull request by aguigan-stripe**

### CODE REVIEW

**Comment by tehben** [comment]
Hi, 
Following the standard upgrade procedure as per [Installing the Stripe Connector for Adobe Commerce (Magento 2)](https://stripe.com/docs/connectors/adobe-commerce/install?locale=en-GB#upgrade) it installs 3.4.4 instead of 3.5.1.
Am I missing something?

**Comment by likearocket** [comment]
> Hi, Following the standard upgrade procedure as per [Installing the Stripe Connector for Adobe Commerce (Magento 2)](https://stripe.com/docs/connectors/adobe-commerce/install?locale=en-GB#upgrade) it installs 3.4.4 instead of 3.5.1. Am I missing something?

Also having the same problem - cannot get 3.5.1 to install via composer. Stripe support is currently taking a week to respond to emails - not great support to be honest.

**Comment by repoUpdateCheck** [comment]
Stripe support is terrible with Adobe extension

**Comment by tehben** [comment]
I got this response from support, which works: 

> When you are using the composer, can you use the command 
> 
> `composer require stripe/module-payments:3.5.1`
>  
> You need to explicitly define the module as 3.5.1 rather than latest. 

However, Test Mode no longer works, so I can't verify if Live mode is functioning correctly.

**Comment by likearocket** [comment]
Doesn't work for me, all I get is:

`  Problem 1
    - Root composer.json requires stripe/module-payments 3.5.1 (exact version match: 3.5.1 or 3.5.1.0), found stripe/module-payments[3.5.1] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - stripe/stripe-payments is locked to version 3.4.0 and an update of this package was not requested.
    - stripe/stripe-payments 3.4.0 requires stripe/module-payments 3.4.* -> found stripe/module-payments[3.4.0, ..., 3.4.4] but it conflicts with your root composer.json require (3.5.1).
`

**Comment by aguigan-stripe** [comment]
Hello, please use our dedicated  support channel, that is accessible through your Stripe dashboard. We are not scanning PR comments for user related technical issues

**Pull request merged**
